###################################
## /collections/requirements.yml ##
###################################
#
# Requirements file for collections to use the project.
---
collections:
  - name: community.general
  - name: ansibleguy.opnsense
