########################################################
## /services/k8s-cluster/production/site.yml             ##
########################################################
#
# Bootstrap and secure the production Kubernetes cluster.

---
- import_playbook: ../cluster-bootstrap.yml
  vars:
    k8s_cluster_name: ts-main-prod
    k8s_control_host_pattern: k8s-control-*
    k8s_worker_host_pattern: k8s-worker-*
    k8s_kube_vip_address: "{{ k8s_kube_prod_vip_address }}"
    k8s_kube_control_endpoint: "{{ k8s_kube_prod_control_endpoint }}"
    k8s_pod_subnet: "{{ k8s_kube_prod_pod_subnet }}"
    k8s_service_subnet: "{{ k8s_kube_prod_service_subnet }}"