#!/usr/bin/env bash
set -euo pipefail
umask 077

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SECRETS_DIR="${REPO_ROOT}/.secrets"
VAULT="Turner-Services-Infra"

die() { echo "Error: $*" >&2; exit 1; }

command -v pass-cli >/dev/null 2>&1 || die "pass-cli not on PATH (install: curl -fsSL https://proton.me/download/pass-cli/install.sh | bash)"
pass-cli info >/dev/null 2>&1 || die "pass-cli not logged in. Run: pass-cli login --interactive <you@proton.me>"

mkdir -p "${SECRETS_DIR}" "${SECRETS_DIR}/ssh" "${SECRETS_DIR}/kubeconfigs"
chmod 700 "${SECRETS_DIR}" "${SECRETS_DIR}/ssh" "${SECRETS_DIR}/kubeconfigs"

fetch() {
  local item="$1" field="$2"
  pass-cli item view --vault-name "${VAULT}" --item-title "${item}" --field "${field}" \
    || die "failed to fetch ${item}/${field}"
}

fetch ts-turneradmin-ssh-privkey      note > "${SECRETS_DIR}/ssh/turneradmin_id_rsa"
fetch ts-turnerans_svc-ssh-privkey    note > "${SECRETS_DIR}/ssh/turnerans_svc_id_rsa"
chmod 600 "${SECRETS_DIR}/ssh/"*_id_rsa

fetch ts-main-prod-kubeconfig         note > "${SECRETS_DIR}/kubeconfigs/ts-main-prod.conf"
fetch ts-main-test-kubeconfig         note > "${SECRETS_DIR}/kubeconfigs/ts-main-test.conf"
chmod 600 "${SECRETS_DIR}/kubeconfigs/"*.conf

local_cluster_hook="${REPO_ROOT}/turner-services-sensitive-repo/ci/materialize-local-cluster-secrets.sh"
if [[ -x "${local_cluster_hook}" ]]; then
  "${local_cluster_hook}" "${VAULT}" "${SECRETS_DIR}"
else
  echo "Warning: ${local_cluster_hook} missing; skipping cluster-specific local secret files" >&2
fi

WIN_TURNERADMIN_PASSWD="$(fetch ts-windows-turneradmin password)"
WIN_TURNERANS_SVC_PASSWD="$(fetch ts-windows-turnerans_svc password)"
PROXMOX_PACKER_USER="$(fetch ts-proxmox-packer-apitoken username)"
PROXMOX_PACKER_APIKEY="$(fetch ts-proxmox-packer-apitoken password)"
PROXMOX_VE_ENDPOINT="$(fetch ts-proxmox-packer-apitoken endpoint)"
UNIFI_API_KEY="$(fetch ts-unifi-apikey password)"
PULUMI_ACCESS_TOKEN_VALUE="$(fetch ts-pulumi-access-token password)"

shq() { printf "%s" "$1" | sed "s/'/'\\\\''/g; s/^/'/; s/$/'/"; }

cat > "${SECRETS_DIR}/env.sh" <<EOF
# Generated by scripts/bootstrap-secrets.sh — re-run to refresh.

export TS_WIN_TURNERADMIN_PASSWD=$(shq "${WIN_TURNERADMIN_PASSWD}")
export TS_WIN_TURNERANS_SVC_PASSWD=$(shq "${WIN_TURNERANS_SVC_PASSWD}")

export TS_PROXMOX_PACKER_USER=$(shq "${PROXMOX_PACKER_USER}")
export TS_PROXMOX_PACKER_APIKEY=$(shq "${PROXMOX_PACKER_APIKEY}")
export PROXMOX_VE_ENDPOINT=$(shq "${PROXMOX_VE_ENDPOINT}")
export PROXMOX_VE_USERNAME=$(shq "${PROXMOX_PACKER_USER}")
export PROXMOX_VE_API_TOKEN=$(shq "${PROXMOX_PACKER_APIKEY}")
export TS_PROXMOX_TOKEN_SECRET=$(shq "${PROXMOX_PACKER_APIKEY}")

export TS_UNIFI_API_KEY=$(shq "${UNIFI_API_KEY}")
export PULUMI_ACCESS_TOKEN=$(shq "${PULUMI_ACCESS_TOKEN_VALUE}")

export TS_TURNERADMIN_SSH_PRIVKEY="${SECRETS_DIR}/ssh/turneradmin_id_rsa"
export TS_TURNERANS_SVC_SSH_PRIVKEY="${SECRETS_DIR}/ssh/turnerans_svc_id_rsa"

export TS_KUBECONFIG_DIR="${SECRETS_DIR}/kubeconfigs"

export TS_CF_DNS01_TOKEN_FILE="${SECRETS_DIR}/cloudflare-dns01-token.txt"
export TS_CODE_SERVER_PASSWORD_FILE="${SECRETS_DIR}/cluster-login-password.txt"
EOF
chmod 600 "${SECRETS_DIR}/env.sh"

unset WIN_TURNERADMIN_PASSWD WIN_TURNERANS_SVC_PASSWD \
      PROXMOX_PACKER_USER PROXMOX_PACKER_APIKEY PROXMOX_TOKEN_SECRET \
      UNIFI_API_KEY PULUMI_ACCESS_TOKEN_VALUE

echo "Wrote secrets to ${SECRETS_DIR}"
echo "Source ${SECRETS_DIR}/env.sh (or open a new shell) to pick up exports."
