#!/usr/bin/env bash
set -euo pipefail
umask 077

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SECRETS_DIR="${REPO_ROOT}/.secrets"
VAULT="Turner-Services-Infra"

die() { echo "Error: $*" >&2; exit 1; }

command -v pass-cli >/dev/null 2>&1 || die "pass-cli not on PATH (install: curl -fsSL https://proton.me/download/pass-cli/install.sh | bash)"
pass-cli info >/dev/null 2>&1 || die "pass-cli not logged in. Run: pass-cli login --interactive <you@proton.me>"

mkdir -p "${SECRETS_DIR}" "${SECRETS_DIR}/ssh" "${SECRETS_DIR}/kubeconfigs"
chmod 700 "${SECRETS_DIR}" "${SECRETS_DIR}/ssh" "${SECRETS_DIR}/kubeconfigs"

fetch() {
  local item="$1" field="$2"
  pass-cli item view --vault-name "${VAULT}" --item-title "${item}" --field "${field}" \
    || die "failed to fetch ${item}/${field}"
}

fetch_single_line() {
  local item="$1" field="$2" path="$3"
  fetch "${item}" "${field}" | tr -d '\r\n' > "${path}"
  chmod 600 "${path}"
}

ensure_secret_file() {
  local path="$1" item="$2" field="$3"
  if [[ ! -s "${path}" ]]; then
    echo "Materializing missing ${path} from ${item}/${field}"
    fetch_single_line "${item}" "${field}" "${path}"
  fi
  [[ -s "${path}" ]] || die "${path} is missing or empty"
  if grep -q 'REPLACE_WITH_' "${path}"; then
    die "${path} still contains placeholder content"
  fi
}

fetch ts-turneradmin-ssh-privkey      note > "${SECRETS_DIR}/ssh/turneradmin_id_rsa"
fetch ts-turnerans_svc-ssh-privkey    note > "${SECRETS_DIR}/ssh/turnerans_svc_id_rsa"
chmod 600 "${SECRETS_DIR}/ssh/"*_id_rsa

fetch ts-main-prod-kubeconfig         note > "${SECRETS_DIR}/kubeconfigs/ts-main-prod.conf"
fetch ts-main-test-kubeconfig         note > "${SECRETS_DIR}/kubeconfigs/ts-main-test.conf"
chmod 600 "${SECRETS_DIR}/kubeconfigs/"*.conf

local_cluster_hook="${REPO_ROOT}/turner-services-sensitive-repo/ci/materialize-local-cluster-secrets.sh"
if [[ -x "${local_cluster_hook}" ]]; then
  "${local_cluster_hook}" "${VAULT}" "${SECRETS_DIR}"
else
  echo "Warning: ${local_cluster_hook} missing; materializing required cluster secret files directly" >&2
fi

ensure_secret_file "${SECRETS_DIR}/cloudflare-dns01-token.txt" ts-cloudflare-dns01-token note
ensure_secret_file "${SECRETS_DIR}/cluster-login-password.txt" ts-code-server-password note
ensure_secret_file "${SECRETS_DIR}/forgejo-db-password.txt" ts-forgejo-db-password note
ensure_secret_file "${SECRETS_DIR}/forgejo-secret-key.txt" ts-forgejo-secret-key note
ensure_secret_file "${SECRETS_DIR}/forgejo-internal-token.txt" ts-forgejo-internal-token note

pbs_answer_hook="${REPO_ROOT}/turner-services-sensitive-repo/ci/materialize-pbs-answer.sh"
if [[ -x "${pbs_answer_hook}" ]]; then
  VAULT="${VAULT}" REPO_ROOT="${REPO_ROOT}" "${pbs_answer_hook}"
fi

WIN_TURNERADMIN_PASSWD="$(fetch ts-windows-turneradmin password)"
WIN_TURNERANS_SVC_PASSWD="$(fetch ts-windows-turnerans_svc password)"
PROXMOX_PACKER_USER="$(fetch ts-proxmox-packer-apitoken username)"
PROXMOX_PACKER_APIKEY="$(fetch ts-proxmox-packer-apitoken password)"
PROXMOX_VE_ENDPOINT="$(fetch ts-proxmox-packer-apitoken endpoint)"
UNIFI_API_KEY="$(fetch ts-unifi-apikey password)"
PULUMI_ACCESS_TOKEN_VALUE="$(fetch ts-pulumi-access-token password)"
GRAFANA_ADMIN_USER="$(fetch ts-grafana-admin username)"

shq() { printf "%s" "$1" | sed "s/'/'\\\\''/g; s/^/'/; s/$/'/"; }

cat > "${SECRETS_DIR}/env.sh" <<EOF
# Generated by scripts/bootstrap-secrets.sh — re-run to refresh.

export TS_WIN_TURNERADMIN_PASSWD=$(shq "${WIN_TURNERADMIN_PASSWD}")
export TS_WIN_TURNERANS_SVC_PASSWD=$(shq "${WIN_TURNERANS_SVC_PASSWD}")

export TS_PROXMOX_PACKER_USER=$(shq "${PROXMOX_PACKER_USER}")
export TS_PROXMOX_PACKER_APIKEY=$(shq "${PROXMOX_PACKER_APIKEY}")
export PROXMOX_VE_ENDPOINT=$(shq "${PROXMOX_VE_ENDPOINT}")
export PROXMOX_VE_USERNAME=$(shq "${PROXMOX_PACKER_USER}")
export PROXMOX_VE_API_TOKEN=$(shq "${PROXMOX_PACKER_APIKEY}")
export TS_PROXMOX_TOKEN_SECRET=$(shq "${PROXMOX_PACKER_APIKEY}")

export TS_UNIFI_API_KEY=$(shq "${UNIFI_API_KEY}")
export PULUMI_ACCESS_TOKEN=$(shq "${PULUMI_ACCESS_TOKEN_VALUE}")

export TS_TURNERADMIN_SSH_PRIVKEY="${SECRETS_DIR}/ssh/turneradmin_id_rsa"
export TS_TURNERANS_SVC_SSH_PRIVKEY="${SECRETS_DIR}/ssh/turnerans_svc_id_rsa"

export TS_KUBECONFIG_DIR="${SECRETS_DIR}/kubeconfigs"

export TS_CF_DNS01_TOKEN_FILE="${SECRETS_DIR}/cloudflare-dns01-token.txt"
export TS_CODE_SERVER_PASSWORD_FILE="${SECRETS_DIR}/cluster-login-password.txt"
export TS_IMMICH_DB_PASSWORD_FILE="${SECRETS_DIR}/immich-db-password.txt"
export TS_NEXTCLOUD_DB_PASSWORD_FILE="${SECRETS_DIR}/nextcloud-db-password.txt"
export TS_NEXTCLOUD_ADMIN_USER_FILE="${SECRETS_DIR}/nextcloud-admin-user.txt"
export TS_NEXTCLOUD_ADMIN_PASSWORD_FILE="${SECRETS_DIR}/nextcloud-admin-password.txt"
export TS_CODER_POSTGRES_PASSWORD_FILE="${SECRETS_DIR}/coder-postgres-password.txt"
export TS_FORGEJO_DB_PASSWORD_FILE="${SECRETS_DIR}/forgejo-db-password.txt"
export TS_FORGEJO_SECRET_KEY_FILE="${SECRETS_DIR}/forgejo-secret-key.txt"
export TS_FORGEJO_INTERNAL_TOKEN_FILE="${SECRETS_DIR}/forgejo-internal-token.txt"
export TS_FORGEJO_RUNNER_UUID_FILE="${SECRETS_DIR}/forgejo-runner-uuid.txt"
export TS_FORGEJO_RUNNER_TOKEN_FILE="${SECRETS_DIR}/forgejo-runner-token.txt"
export TS_GRAFANA_ADMIN_PASSWORD_FILE="${SECRETS_DIR}/grafana-admin-password.txt"
export TS_GRAFANA_ADMIN_USER=$(shq "${GRAFANA_ADMIN_USER}")
export PBS_AUTOINSTALL_ANSWER_FILE="${REPO_ROOT}/turner-services-sensitive-repo/proxmox-backup-server/answer.toml"
EOF
chmod 600 "${SECRETS_DIR}/env.sh"

unset WIN_TURNERADMIN_PASSWD WIN_TURNERANS_SVC_PASSWD \
      PROXMOX_PACKER_USER PROXMOX_PACKER_APIKEY PROXMOX_TOKEN_SECRET \
      UNIFI_API_KEY PULUMI_ACCESS_TOKEN_VALUE GRAFANA_ADMIN_USER

echo "Wrote secrets to ${SECRETS_DIR}"
echo "Source ${SECRETS_DIR}/env.sh (or open a new shell) to pick up exports."
